_BASE_: "../M2F_ResNet50_base_ignore255.yaml"
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.1
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "lowAltitude_segmentation/Mask2Former/ADE20K_Swin-L (IN21k).pkl"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval [ "[int(x * 0.1 * 1024) for x in range(5, 21)]" ]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 128
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 500
  AUG:
    ENABLED: False
    MIN_SIZES: [ 320, 480, 640, 800, 960, 1120 ]
    MAX_SIZE: 4480
    FLIP: True
